#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# INSTALL JAVA SE 21 if chosen 
#=================================================
ynh_script_progression "checking up source if needed..."
if [[ $JAVAVERSION == "JavaSE-21" ]]; then
    wget -N -O /tmp/jdk-21_linux-x64_bin.deb https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
    sudo dpkg -i /tmp/jdk-21_linux-x64_bin.deb
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

if [ "$version" = "Enterprise" ]; then
  ynh_setup_source --dest_dir="$install_dir" --source_id="enterprise"
elif [ "$version" = "Community" ]; then
  ynh_setup_source --dest_dir="$install_dir" --source_id="main"
elif [ "$version" = "Latest" ]; then
  ynh_setup_source --dest_dir="$install_dir" --source_id="latest"
fi

chmod +x $install_dir/metabase.jar

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Web database management tool" --log="/var/log/$app/$app.log"

#=================================================
# SETUP CONFIG
#=================================================
ynh_script_progression "Adding $app's configuration..."

touch /etc/default/$app
ynh_config_add --template="metabase" --destination="/etc/default/$app"

chmod 640 "/etc/default/$app"
chown $app "/etc/default/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd --wait_until="Please use the following URL to setup your Metabase installation:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
